language: ruby
before_install:
  - gem install bundler
bundler_args: --binstubs
branches:
  only:
    - devel/try
script: "ruby -w ./test/suite.rb"
rvm:
  - ruby-head
  - 2.2.2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
    - rvm: rbx-18mode
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: jruby-18mode
    - rvm: ree
notifications:
  email:
    recipients:
      - stef@youdontneedacrm.com
